language: go

go:
  - "1.14"
  - tip

jobs:
  include:
    - stage: test
      script: go test -cover -tags test -race -timeout 30s ./...
    - stage: vet
      script: go vet ./...
    - stage: build
      script: go build -v -o airplay.o cmd/main.go
